apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mmoo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbqk-tenant/rhtap-demo-app/hacbs-test-project-mmoo@sha256:707816c282aa603dd8d9d92fa426a7b411806f0f4045ad2ff3b27fb15c8317b9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
