apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mmoo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mmoo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mmoo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mmoo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mmoo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbqk-tenant/rhtap-demo-app/hacbs-test-project-mmoo@sha256:629e69898e46b5a51bdd961172ff3cf596ab17955ab6fb96e9dc7957dc0749b6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
